### ISSUE TITLE
Practical 1 > 5.1 Goal-oriented approach 

### ISSUE THREAD

**Issue by willdkreid** [rasanderson/NES2303_Practical1#29] opened 2023-07-24 14:40 UTC
Practical 1 > 5.1 Goal-oriented approach > paragraph 2 bullet point 3
1. remove "is" and change to "the reverse cannot be true"

Practical 1 > 5.1 Goal-oriented approach > paragraph 4
- say how to print the values on screen after they have been stored e.g. "Nothing is actually printed on screen when you store the data but it be accessed by just typing the temporary variable name you gave it."

Practical 1 > 5.1 Goal-oriented approach > paragraph 5
- if the outlier inforamtion in the interactive webpages changes then this needs edited

**Comment by rasanderson** [comment] 2023-08-08 16:22
First two suggestions completed. Link to interactive website will need updating.

**Comment by rasanderson** [comment] 2023-08-09 14:44
As final point that is still outstanding is a duplicate of #36 closing this for now

**Closed as completed by rasanderson** 2023-08-09 14:44 UTC
